"""
Django settings for slack_bot_project project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yncli3asu_^qang#$r_m58k+g6#%+ju5v$84u&+%dnq!s4q=v_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['24fd2c08.ngrok.io', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'slack_bot_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'slack_bot_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'slack_bot_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/slack_bot/'
LOGIN_REDIRECT_URL = '/slack_bot/'
# SLACK_CLIENT_ID = "282559645383.281995592243"
# SLACK_CLIENT_SECRET = "2b1de09566d7f75d5f136b27d01b528d"
# SLACK_VERIFICATION_TOKEN = "ILSgrn9lnDCCnxer6w1ja0G1"
# test_bot
# VERIFICATION = 'xoxb-282760423058-7bNAPDuUpUsqaeXILoFMjwUs'
# OAUTH = 'xoxp-282559645383-280970212289-282103807136-d052ddbf15b978f72767301fa0bf864c'
# SLACK_CLIENT_ID = '282559645383.283784960919'
# SLACK_CLIENT_SECRET = 'df1831c62c0354123c5f993b8fa6e12c'
# SLACK_VERIFICATION_TOKEN = 'nXvaez0T0b6w5cdahdYKDT4u'

# workbot
# SLACK_BOT_TOKEN = "xoxb-283146722036-v8pYN2wwFJ005hmqhiQo7SM0"
# BOT_ID = "U8B4AM812"
# test work
SLACK_CLIENT_ID = "282559645383.283555506357"
SLACK_CLIENT_SECRET =  "297245be757f75f5039b7d69aae36845"
SLACK_VERIFICATION_TOKEN = "Qa9ArSmt4LpuZI9NurUXOKBs"
SLACK_BOT_TOKEN = "xoxb-283146722036-v8pYN2wwFJ005hmqhiQo7SM0"